### PR TITLE
Documentation mini site 🖌️ 

### PR DESCRIPTION
**Pull request by peteryates**
We intend to publish the contents of the [documentation directory](https://github.com/DFE-Digital/ecf2/tree/main/documentation) to a static website that's easy to navigate to and we can easily use for cross-referencing purposes.

The site will be located in the 'documentation/site' directory and will share the `Gemfile` and `package.json` with the main Rails app to keep dependencies tidy.

It needs to be written in Ruby because we use [Asciidoctor](https://asciidoctor.org/) for the policy docs and we opted for [Nanoc](https://nanoc.app/) for its flexibility and simplicity.

image

## Final tasks

* [ ] Review content, fix any broken links and dodgy formatting
* [x] Get the policy and contract documents rendering (this will require [Asciidoctor](https://asciidoctor.org/))
* [x] Make the homepage look nicer 💅🏽 
* [x] Add title to the header and maybe some relevant links to the footer
* [x] Add the glossary page
* [x] Get it automatically publishing on GitHub Pages
* [x] Move the 'Key' tables to a shared partial

### CODE REVIEW

**Review by tonyheadford — APPROVED** [review]
Looks really clean!

**Comment by peteryates** [comment]
@claire-hughez I suspect we'll end up sticking this on an `.education.gov.uk` domain. Thoughts on whether it should be in GOV.UK or DfE colours?

**Comment by peteryates** [comment]
There are now a couple of `make` commands that help previewing changes we make to docs a little easier :)


https://github.com/user-attachments/assets/465ab094-ab1d-4b8f-9aa8-bdccf88b9118

**Comment by EmmaFrith** [comment]
# Tidying up the homepage


Screenshot 2024-08-06 at 16 58 36

# Creating a key on the service rules page

Screenshot 2024-08-06 at 16 59 27

## Using different templates for different content types so that we can have relevant captions:

Screenshot 2024-08-06 at 17 00 05

Screenshot 2024-08-06 at 17 02 46

**Comment by gracecbrennan** [comment]
Still quite a bit of work to do on this but making good progress.

**Comment by peteryates** [comment]
@claire-hughez made the excellent suggestion of adding a roadmap style page to this site.

Here are some examples of nice public roadmaps:

* [NHS UK](https://digital.nhs.uk/services/nhs.uk/nhs.uk-roadmap-and-strategy)
* [GOV.UK Design System](https://design-system.service.gov.uk/community/roadmap/)
* [GOV.UK](https://www.gov.uk/roadmap)

@EmmaFrith I think this is probably a follow up piece as everything's currently in flux.

**Comment by peteryates** [comment]
Maybe we could have a page covering what's suggested in #72 too.

**Comment by EmmaFrith** [comment]
The site is now published on [GitHub Pages](https://dfe-digital.github.io/ecf2/). Doesn't fully work yet as we're waiting for a domain. Will do the final task (Review content, fix any broken links and dodgy formatting) in a separate PR.
@tonyheadford could you maybe give this another look before we merge?

**Review by EmmaFrith — APPROVED** [review]

**Pull request merged**
